from model.model import HealingHistory, ResultPredict, HistoryNeuralNetwork, Annotations, Patient
from repository.PatientRepository import PatientRepository
from repository.ResultPredictRepository import ResultPredictRepository